version: '3'
services:
    php:
        build:
            context: .
            dockerfile: Dockerfile
        image: scrapy/scrapy:7.4.2
        command: tail -f /dev/null
        volumes:
            - .:/var/www/scrapy
